- name: Create disks(s) and instance(s)
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    machine_type: n1-standard-2 # default
    image: centos-7
    hosts:
      - gluster-client-1
      - gluster-client-2
    state: active

  tasks:
    - name: Launch instances
      gce:
          instance_names: "{{ hosts|join(',') }}"
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          tags: gluster-clients
          zone: us-east1-b
          state: "{{ state }}"
          service_account_permissions:
          - logging-write
          - monitoring
      register: gce

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
      with_items: "{{gce.instance_data | default({})}}"

    - name: Add host to gluster group
      add_host: hostname={{ item.public_ip }} groupname=gluster-clients
      with_items: "{{gce.instance_data | default({})}}"

- name: Configure instance(s) with gluster-client
  hosts: gluster-clients
  become: true
  vars:
    mount_device: gluster-1b:/share
    mount_point: /mnt
    fstype: glusterfs
  roles:
    - stackdriver_agent
    - client
