- name: Install the EPEL repo
  yum: name=epel-release
- name: Install gluster repo
  yum: name=centos-release-gluster
- name: Install PIP
  yum: name=python-pip
- name: Install Gluster client
  yum: name=glusterfs-client
- name: Install NFS utils
  yum: name=nfs-utils
- name: Mount shared filesystem
  mount: name={{ mount_point }} src={{ mount_device }} fstype={{ fstype }} state=mounted
- name: Create sysbench test file directory
  file: state=directory path={{ mount_point }}/{{ ansible_hostname }}
- name: Install sysbench
  yum: name=sysbench
- name: Generate files for sysbench test
  command: chdir={{ mount_point }}/{{ ansible_hostname }} sysbench --test=fileio --file-total-size=16G prepare creates={{ mount_point }}/{{ ansible_hostname }}/test_file.*
- name: Run sysbench
  shell: chdir={{ mount_point }}/{{ ansible_hostname }} sysbench --test=fileio --file-total-size=16G --file-test-mode={{ fileio_test }} --max-time=60 --max-requests=0 --file-block-size=4K --num-threads=4 --file-fsync-all run | grep 'Total transferred'
  register: sysbench
- debug: var=sysbench.stdout
