- name: Install the EPEL repo
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
- name: Install gluster repo
  get_url: url=http://download.gluster.org/pub/gluster/glusterfs/LATEST/EPEL.repo/glusterfs-epel.repo dest=/etc/yum.repos.d/glusterfs-epel.repo
- name: Install Gluster client
  yum: name=glusterfs-client
- name: Mount Gluster filesystem
  mount: name={{ mount_point }} src={{ mount_device }} fstype=glusterfs state=mounted
- name: Install sysbench
  yum: name=sysbench
- name: Generate files for sysbench test
  command: chdir={{ mount_point }} sysbench --test=fileio --file-total-size=16G prepare
- name: Run sysbench
  command: chdir={{ mount_point }} sysbench --test=fileio --file-total-size=16G --file-test-mode=rndrw --max-time=240 --max-requests=0 --file-block-size=4K --num-threads=4 --file-fsync-all run
  register: sysbench
- debug: var=sysbench.stdout_lines
