- name: install the epel rpm
  yum: name=epel-release
- name: install gluster repo
  yum: name=centos-release-gluster
- name: install gluster server
  yum: name=glusterfs-server
- name: start and enable glusterd
  service: name=glusterd enabled=yes state=started
- name: Create XFS filesystem on data device
  filesystem: fstype=xfs dev=/dev/sdb force=yes
- name: Create brick directory
  file: name={{ mount_point }} state=directory
- name: Mount XFS filesystem
  mount: name={{ mount_point }} src=/dev/sdb fstype=xfs state=mounted
- name: Peer hosts
  action: command gluster peer probe {{ item.1 }}
  register: result
  until: result|success
  retries: 5
  delay: 10
  with_subelements:
    - "{{volumes}}"
    - hosts
- name: Set sysctl parameters
  sysctl: name={{item.name}} value={{item.value}} state=present sysctl_set=yes reload=yes
  with_items: "{{sysctl}}"
