- name: Download script
  get_url: url=https://repo.stackdriver.com/stack-install.sh dest=/root/stack-install.sh
- name: Install Stackdriver Agent
  shell: bash /root/stack-install.sh  --api-key={{ stackdriver_api_key }} creates=/opt/stackdriver/
- name: Download script
  get_url: url=https://dl.google.com/cloudagents/install-logging-agent.sh dest=/root/logger-install.sh
- name: Install Cloud Logging agent
  shell: bash /root/logger-install.sh creates=/opt/google-fluentd/
