- name: Download script
  get_url: url=https://repo.stackdriver.com/stack-install.sh dest=/root/stack-install.sh 
- name: Install Stackdriver Agent
  shell: bash /root/stack-install.sh --api-key={{ stackdriver_api_key }}
